# Generated by Django 2.0.2 on 2020-07-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
    ]
