# Generated by Django 2.0.2 on 2020-07-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180305_1855'),
        ('blog', '0003_auto_20200704_1610'),
    ]

    operations = [
    ]
